config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '' , path_names: {sign_in:'login', sign_out: 'logout', sign_up: 'register'}
  resources :portfolios, except: [:show]

  get 'react-portfolio', to: 'portfolios#react'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  resources :blogs do 
  	member do
  		get :toggle_status
  	end
  end

  root to:'pages#home'
  resources :topics
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
	enum status: {draft: 0, published: 1}
	extend FriendlyId
  friendly_id :title, use: :slugged

  validates_presence_of :title, :body
end

app/models/concerns/placeholder.rb
module Placeholder
	extend ActiveSupport::Concern

	def self.image_generator(height:, width:)
		"http://placehold.it/#{height}x#{width}"
	end
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
	include Placeholder

	has_many :technologies
	
	def self.react
  	where(subtitle: 'React')
  end

  scope :ruby_on_rails, -> {where(subtitle: 'Ruby on Rails')}
	validates_presence_of :title, :body, :main_image, :thumb_image

	after_initialize :set_defaults

	def set_defaults
		self.main_image ||= Placeholder.image_generator(height: '600',width: '400')
		self.thumb_image ||= Placeholder.image_generator(height: '350',width: '200')
	end
end

app/models/skill.rb
class Skill < ApplicationRecord
	include Placeholder
	validates_presence_of :title, :percent_utilized

	after_initialize :set_defaults

	def set_defaults
		self.badge ||= Placeholder.image_generator(height: '250',width: '250')
	end
end

app/models/technology.rb
class Technology < ApplicationRecord
  belongs_to :portfolio
end

app/models/topic.rb
class Topic < ApplicationRecord
	validates_presence_of :title
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates_presence_of :name

  def first_name
  	self.name.split.first
  end

  def last_name
  	self.name.split.last
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
	include DeviseWhitelist
  include SessionSource
  include CurrentUserConcern
  include DefaultPageContent

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy, :toggle_status]
  layout "blog"

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    @page_title = @blog.title
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def toggle_status
    if @blog.published?
      @blog.draft!
    else
      @blog.published!
    end
    redirect_to blogs_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :body)
    end
end

app/controllers/concerns/current_user_concern.rb
module CurrentUserConcern
	extend ActiveSupport::Concern

	def current_user
  	super || guest_user
  end

  def guest_user
  	OpenStruct.new(name:"Guest User", 
  								 first_name:"Guest", 
  								 last_name:"User", 
  								 emaiL:"guest@example.com"
  								 )
  end
  
end

app/controllers/concerns/default_page_content.rb
module DefaultPageContent
	extend ActiveSupport::Concern 

	included do 
	  before_action :set_title
  end

  def set_title	
  	@page_title = "Mike's Portfolio | Stuff I do"
  	@seo_keywords = "Marvellous Michaels Portfolio"
  end
end

app/controllers/concerns/devise_whitelist.rb
module DeviseWhitelist
	extend ActiveSupport::Concern

	included do 
	  before_action :config_params, if: :devise_controller?
  end

	def config_params
		devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
		devise_parameter_sanitizer.permit(:account_update, keys: [:name])
	end
end

app/controllers/concerns/session_source.rb
module SessionSource
	extend ActiveSupport::Concern

	included do
				before_action :set_source
	end

	def set_source
	  session[:source] = params[:q] if params[:q]
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	
  def home
  end

  def about
  end

  def contact
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio_item, only:[:edit, :update, :show, :destroy]
  layout "portfolio"
	def index
		@portfolio_items = Portfolio.all
	end

  def react
    @react_portfolio_items = Portfolio.react
  end

	def new
		@portfolio_item = Portfolio.new
    3.times{ @portfolio_item.technologies.build }
	end

	def create
	  @portfolio_item = Portfolio.new(portfolio_params)

    respond_to do |format|
      if @portfolio_item.save
        format.html { redirect_to portfolios_path, notice: 'Portfolio was successfully created.' }
      else
        format.html { render :new,notice: 'Portfolio was not created.' }
      end
    end
	end

	def edit
    3.times{ @portfolio_item.technologies.build }
	end

	def update
    respond_to do |format|
      if @portfolio_item.update(portfolio_params)
        format.html { redirect_to portfolios_url, notice: 'Item was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def show
  end

  def destroy
  	@portfolio_item.destroy
  	respond_to do |format|
  		format.html {redirect_to portfolios_path, notice: 'Item Deleted'}
  	end
  end

  private

  def portfolio_params
    params.require(:portfolio).permit(:title, :subtitle, :body, :thumb_image, :main_image, technologies_attributes: [:name])
  end

  def set_portfolio_item
    @portfolio_item = Portfolio.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def login_helper
		 if current_user.is_a?(User)
       link_to "Logout", destroy_user_session_path, method: :delete
     else
        (link_to "Register", new_user_registration_path) + "<br>".html_safe +
        (link_to "Login", new_user_session_path)
     end
	end

	def source_helper
	  if session[:source]
	    greeting = "Thanks for visiting me from #{session[:source]}"
	    content_tag[:p, greeting , class: "source-greeting"]
	  end
	end

end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/blogs/_blog.html.erb
<tr>
  <td><%= blog.title.upcase %></td>
  <td>Published <%= distance_of_time_in_words(blog.created_at, Time.now) %> ago</td>
  <td><%= blog.body %></td>
  <td><%= link_to blog.status, toggle_status_blog_path(blog) %></td>
  <td><%= link_to 'Show', blog %></td>
  <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
  <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
        <% blog.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blogs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%= render @blogs %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @blog.body %>
</p>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @page_title %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="keywords" content="<%= @seo_keywords %>">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= render "shared/nav", location:"top" %>

    <% if current_user.is_a?(User) %>
    <%= link_to "Logout", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "Register", new_user_registration_path %>
      <%= link_to "Login", new_user_session_path %>
    <% end %>
    <%= yield %>

    <% if session[:source] %>
      <p> Thanks for visiting us from <%= session[:source] %> </p>
    <% end %>
  </body>
</html>

app/views/layouts/blog.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @page_title %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="keywords" content="<%= @seo_keywords %>">

    <%= stylesheet_link_tag 'blogs', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>


    <% if current_user.is_a?(User) %>
    <%= link_to "Logout", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "Register", new_user_registration_path %>
      <%= link_to "Login", new_user_session_path %>
    <% end %>
    <%= yield %>

    <%= render "shared/nav", location: "bottom" %>

    <% if session[:source] %>
      <p> Thanks for visiting us from <%= session[:source] %> </p>
    <% end %>
  </body>
</html>

app/views/layouts/portfolio.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @page_title %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="keywords" content="<%= @seo_keywords %>">

    <%= stylesheet_link_tag 'portfolios', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>


    <% if current_user.is_a?(User) %>
    <%= link_to "Logout", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "Register", new_user_registration_path %>
      <%= link_to "Login", new_user_session_path %>
    <% end %>
    <%= yield %>

    <%= render "shared/nav", location: "bottom" %>

    <% if session[:source] %>
      <p> Thanks for visiting us from <%= session[:source] %> </p>
    <% end %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>

<p><%= number_to_phone "08034143461" %></p>

app/views/pages/home.html.erb
<h1>Hi <%= current_user.first_name%></h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/portfolios/_form.html.erb
<%= form_for(@portfolio_item) do |form| %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :subtitle %>
    <%= form.text_field :subtitle %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <ul>
    <%= form.fields_for :technologies do |technology_form| %>
    <li>
      <%=technology_form.label :name %>
      <%= technology_form.text_field :name %>
    </li>
    <% end %>
  </ul>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/portfolios/_portfolio_item.html.erb
<p><%= link_to portfolio_item.title , portfolio_show_path(portfolio_item) %></p> 
  <%= link_to "Edit Item", edit_portfolio_path(portfolio_item) %>
  <p><%= portfolio_item.subtitle %></p>
  <p><%= portfolio_item.body %></p>
  <p><%= image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil? %></p>
  <%= link_to "Delete Portfolio Item", portfolio_path(portfolio_item), method: :delete, data: {confirm: "Are you sure?"} %>

app/views/portfolios/edit.html.erb
<h2>Edit Portfolio Item</h2>

<%= render 'form', portfolio_item: @portfolio_item %>

app/views/portfolios/index.html.erb
<h2>Portfolio</h2>

<%= link_to "Create New Portfolio", new_portfolio_path %>

<%= render partial: 'portfolio_item', collection: @portfolio_items %>
  
<% end %>

app/views/portfolios/new.html.erb
<h2>Create New </h2>

<%= render 'form', portfolio_item: @portfolio_item %>

app/views/portfolios/react.html.erb
<h2>React Portfolio</h2>

<%= link_to "Create New React Portfolio", new_portfolio_path %>

<% @react_portfolio_items.each do |portfolio_item| %>
  <p><%= link_to portfolio_item.title , portfolio_show_path(portfolio_item) %></p> 
  <%= link_to "Edit Item", edit_portfolio_path(portfolio_item) %>
  <p><%= portfolio_item.subtitle %></p>
  <p><%= portfolio_item.body %></p>
  <p><%= image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil? %></p>
  <%= link_to "Delete Portfolio Item", portfolio_path(portfolio_item), method: :delete, data: {confirm: "Are you sure?"} %>
<% end %>

app/views/portfolios/show.html.erb
<%= image_tag @portfolio_item.thumb_image %>

<%= @portfolio_item.title %>

<%= @portfolio_item.subtitle %>

<%= @portfolio_item.body %>

<h2>Technologies used</h2>

<% @portfolio_item.technologies.each do |item| %>
	<p><%= item.name %> </p>
<% end %>

app/views/shared/_nav.html.erb
 <div class="<%= location %>">
      <div><%= link_to "Home", root_path %></div>
      <div><%= link_to "About", about_path %></div>
      <div><%= link_to "Contact", contact_path %></div>
      <div><%= link_to "Blog", blogs_path %></div>
      <div><%= link_to "Portfolio", portfolios_path %></div>
    </div>